# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  release:
    needs:
      - build
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.2
    with:
      prerelease: false
      tag_name: ${{ github.ref_name }}
      release_files: |
        artifacts-*/*
        toml.bzl-*.tar.gz

  publish:
    needs: release
    uses: ./.github/workflows/publish.yaml
    with:
      tag_name: ${{ github.ref_name }}
    secrets:
      BCR_PUBLISH_TOKEN: ${{ secrets.BCR_PUBLISH_TOKEN }}
